from typing import Any, Protocol

class MotorCollection(Protocol):
    async def insert_one(self, document: Any) -> Any: ...
    def find(self, *args: Any, **kwargs: Any) -> Any: ...
    async def find_one(self, *args: Any, **kwargs: Any) -> Any: ...
    async def update_one(self, *args: Any, **kwargs: Any) -> Any: ...
    async def delete_one(self, *args: Any, **kwargs: Any) -> Any: ...
    def aggregate(self, *args: Any, **kwargs: Any) -> Any: ...
    async def count_documents(self, *args: Any, **kwargs: Any) -> int: ...
